apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  selector:
    matchLabels:
      app: pma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - image: pma_image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        name: pma
        ports:
        - containerPort: 5000
          name: pma
---
apiVersion: v1
kind: Service
metadata:
  name: pma-svc
  labels:
    app: pma
  annotations:
    metallb.universe.tf/allow-shared-ip: kubernetes
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: pma